### ISSUE TITLE
Failed integration with pylint >= 2.0.0

### ISSUE THREAD

**Issue by shiro-saber** [vicenteneto/flask-ci#24]
The package doesn't support pylint newer than version 1.9 because a change on the arguments of `lint.Run()`.

I'm pasting the traceback:
```
Traceback (most recent call last):
  File "manage.py", line 34, in <module>
    manager.run()
  File "/home/nds/Documents/Banorte/chatbot-api/venv/lib/python3.7/site-packages/flask_script/__init__.py", line 417, in run
    result = self.handle(argv[0], argv[1:])
  File "/home/nds/Documents/Banorte/chatbot-api/venv/lib/python3.7/site-packages/flask_script/__init__.py", line 386, in handle
    res = handle(*args, **config)
  File "/home/nds/Documents/Banorte/chatbot-api/venv/lib/python3.7/site-packages/flask_ci/ci.py", line 60, in __call__
    task.run(self.settings, **kwargs)
  File "/home/nds/Documents/Banorte/chatbot-api/venv/lib/python3.7/site-packages/flask_ci/tasks/run_pylint.py", line 42, in run
    lint.Run(args, reporter=ParseableTextReporter(output=output), exit=False)
TypeError: <flask_ci.ci.CICommand object at 0x7fc28d6e1f60>: __init__() got an unexpected keyword argument 'exit'
```

And my environment:
```
python     3.7.0
Flask      1.0.2
Flask CI   1.2.9.1
pylint     2.1.1
```

**Comment by shiro-saber** [comment]
I took the freedom of make the change of the package, checking the `pylint` version and then use the correct function call format that fits with the pylint version.

I opened a pull request which is the next.
https://github.com/vicenteneto/flask-ci/pull/23

Greetings
